
const All_Movie_SliderData = [
    {
        id: 1,
        title: "MORTAL KOMBAT",
        className:"mortal_kombat",
        imageSrc: "https://4kwallpapers.com/images/wallpapers/mortal-kombat-2021-movies-poster-2560x1080-4902.jpg",
        category: "hollywood",
        subcategory: "action",
        movieDiscription:"It is the Taisho Period in Japan. Tanjiro, a kindhearted boy who sells charcoal for a living, finds his family slaughtered by a demon. To make matters worse, his younger sister Nezuko, the sole survivor, has been transformed into a demon herself...",
        videoSrc: "https://cdn.jwplayer.com/players/6ieuvVCM-Twc0KgD2.html",
    },

    {
        id: 2,
        title: "AVATAR 2",
        className:"avatar interNationalMovie",
        imageSrc: "/image/Avatar.webp",
        category: "hollywood",
        subcategory: "action",
        movieDiscription:"It is the Taisho Period in Japan. Tanjiro, a kindhearted boy who sells charcoal for a living, finds his family slaughtered by a demon. To make matters worse, his younger sister Nezuko, the sole survivor, has been transformed into a demon herself...",
        videoSrc: "https://cdn.jwplayer.com/players/he8BSL4B-Twc0KgD2.html",
    },
 
   
 
    {
        id: 3,
        title: "INCEPTION",
        className:"inception interNationalMovie",
        imageSrc: "https://w.forfun.com/fetch/3d/3de6d3916fb8b93ec59b74976550d488.jpeg",
        category: "hollywood",
        subcategory: "action",
        movieDiscription:"Denji is a young boy who works as a Devil Hunter with the Chainsaw Devil Pochita One day as he was living his miserable life trying to pay off the debt he inherited from his parents  he got betrayed and killed. As he was losing his consciousness...",
        videoSrc: "https://cdn.jwplayer.com/players/YI1Uqzel-Twc0KgD2.html",
    },
   
    {
        id: 4,
        title: "WAKANDA FOREVER",
        className:"wakanda_forever",
        imageSrc: "https://m.media-amazon.com/images/S/pv-target-images/8c579c1b0ee1e3dfd99c2a33a740982a67fd230c3e1126b23ec907116d116741.jpg",
        category: "hollywood",
        subcategory: "action",
        movieDiscription:"Denji is a young boy who works as a Devil Hunter with the Chainsaw Devil Pochita. One day as he was living his miserable life trying to pay off the debt he inherited from his parents  he got betrayed and killed. As he was losing his consciousness...",
        videoSrc: "https://cdn.jwplayer.com/players/QMB2h2pN-Twc0KgD2.html",
    },

    {
        id: 5,
        title: "AVENGER ENDGAME",
        className:"avenger_endgame",
        imageSrc: "https://www.koimoi.com/wp-content/new-galleries/2023/04/relive-the-6-top-moments-from-marvels-avengers-endgame-available-on-disney-hotstar-on-its-4th-anniversary-01.jpg",
        category: "hollywood",
        subcategory: "action",
        movieDiscription:"With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos's actions and undo the chaos to the universe, no matter what consequences may be in store, and no matter who they face Avenge the fallen...",
        videoSrc: "https://cdn.jwplayer.com/players/RwZmdfPo-Twc0KgD2.html",
    },
   
    {
        id: 6,
        title: "THE BATMAN",
        className:"The_dark_knight interNationalMovie",
        imageSrc: "https://w0.peakpx.com/wallpaper/307/244/HD-wallpaper-the-batman-movie-poster-art-the-batman-batman-superheroes-movies-2022-movies.jpg",
        category: "hollywood",
        subcategory: "action",
        movieDiscription:"Batman, Lieutenant James Gordon, and new District Attorney Harvey Dent successfully begin to round up the criminals that plague Gotham City, until a mysterious and sadistic criminal mastermind known only as The Joker appears in Gotham, creating a new wave of chaos...",
        videoSrc: "https://cdn.jwplayer.com/players/wP1JlDZk-Twc0KgD2.html",
    },
   
    {
        id: 7,
        title: "EXTRA CURRICULAR",
        className:"extra_curricular",
        imageSrc: "https://www.heavenofhorror.com/wp-content/uploads/2020/04/Extracurricular-netflix-review.jpg",
        category: "koreandrama",
        subcategory: "action",
        movieDiscription:"It is a story of high school students who become tangled in a series of conflicts and events that challenge human values and morality. Jisoo (Kim Dong-Hee) is a model high school student. To pay for his university tuition fee, he makes a bad choice. This leads to a serious crime that takes place...",
        videoSrc: "https://cdn.jwplayer.com/players/ilAfyy5F-Twc0KgD2.html",
    },
   
    {
        id: 8,
        title: "THE CALL",
        className:"the_call interNationalMovie",
        imageSrc: " https://www.heavenofhorror.com/wp-content/uploads/2020/11/the-call-2020-netflix-review-1.jpg",
        category: "koreandrama",
        subcategory: "action",
        movieDiscription:"Seo-yeon, 28, takes the train to the South Korean countryside to visit her hospitalized mom. Having lost her smartphone on the train, she finds a phone in her mom's house. She finds a hidden basement and Young-sook's 20 year old/Nov.1999 diary when she, too, was 28...",
        videoSrc: "https://cdn.jwplayer.com/players/CicjxPCx-Twc0KgD2.html",
    },
    {
        id: 9,
        title: "ALL OF US ARE DEAD",
        className:"all_of_us_are_dead",
        imageSrc: "https://e0.pxfuel.com/wallpapers/559/269/desktop-wallpaper-netflix-s-all-of-us-are-dead-is-the-k-drama-zombie-survival-series-we-always-wanted-our-review-geek-outpost-yoon-gwi-nam.jpg",
        category: "koreandrama",
        subcategory: "action",
        movieDiscription:"It was a normal school day for the students of a Korean high school-until a student returns from the school's science lab, infected by an unknown virus. As the infection spreads out of school and throughout the peninsula, the Military desperately interrogates the psychotic science teacher...",
        videoSrc: "https://cdn.jwplayer.com/players/VnKAvOrm-Twc0KgD2.html",
    },
  
    {
        id: 10,
        title: "SILENCE KILLS MIDNIGHT",
        className:"silence_kills_midnight",
        imageSrc: "https://images-na.ssl-images-amazon.com/images/S/pv-target-images/855299345a2497e7165323e77ced2781b1dea25633b7738d9a1e1631ba382495._UY500_UX667_RI_TTW_.png",
        category: "koreandrama",
        subcategory: "action",
        movieDiscription:"Fear grips the country of South Korea as a serial killer talks its residents. Kyung-mi, a deaf woman, is out late with her mother when she stumbles upon a young woman bleeding out in a dark alley. Now a witness to the killer's brutal crime, Kyung-mi is being ruthlessly hunted down. Will she survive...",
        videoSrc: "https://cdn.jwplayer.com/players/OZnbdqid-Twc0KgD2.html",
    },
    {
        id: 11,
        title: "PARASITE",
        className:"parasite interNationalMovie",
        imageSrc: "https://img.onmanorama.com/content/dam/mm/en/entertainment/entertainment-news/images/2020/4/14/korean-movies-like-parasite.jpg",
        category: "koreandrama",
        subcategory: "action",
        movieDiscription:"The Kims - mother and father Chung-sook and Ki-taek, and their young adult offspring, son Ki-woo and daughter Ki-jung - are a poor family living in a shabby and cramped half basement apartment in a busy lower working class commercial district of Seoul. Ki-woo is the one who has dreams of getting out...",
        videoSrc: "https://cdn.jwplayer.com/players/5Li1CzsT-Twc0KgD2.html",
    },
    {
        id: 12,
        title: "THE SQUID GAME",
        className:"the_squid_game",
        imageSrc: "https://wallpapers.com/images/featured/squid-game-fvsfw2qlkey7u5o8.jpg",
        category: "koreandrama",
        subcategory: "action",
        movieDiscription:"456 real players will enter the game in pursuit of a life-changing reward of $4.56 million. As they compete through a series of games inspired by the original show, plus surprising new additions, their strategies, alliances, and character will be put to the test while competitors are eliminated around them...",
        videoSrc: "https://cdn.jwplayer.com/players/KNn2EaGM-Twc0KgD2.html",
    },
    {
        id: 13,
        title: "THE WITCH",
        className:"the_witch interNationalMovie",
        imageSrc: "https://miro.medium.com/v2/resize:fit:1358/0*7dnxFO6L3xRxvpjP.jpeg",
        category: "koreandrama",
        subcategory: "action",
        movieDiscription:"New England, 1630: William and Katherine try to lead a devout Christian life, homesteading on the edge of an impassible wilderness, with five children. When their newborn son mysteriously vanishes and their crops fail, the family begins to turn on one another...",
        videoSrc: "https://cdn.jwplayer.com/players/DPvjTufp-kh0barMv.html",
    },
    {
        id: 14,
        title: "DEMON SLAYER",
        className:"demon_slayer interNationalMovie",
        imageSrc: "/image/demon.webp",
        category: "anime",
        subcategory: "action",
        movieDiscription:"Tanjiro Kamado, a young boy living in Taisho-era Japan. A family is attacked by demons and only two members survive  Tanjiro and his sister Nezuko, who is turning into a demon slowly. Tanjiro sets out to become a demon slayer to avenge his family and cure his sister...",
        videoSrc: "https://cdn.jwplayer.com/players/HbuWrNJG-Twc0KgD2.html",
    },
    {
        id: 15,
        title: "Dr. STONE",
        className:"dr_stone interNationalMovie",
        imageSrc: "/image/DrStone.webp",
        category: "anime",
        subcategory: "action",
        movieDiscription:"One fateful day, all of humanity was petrified by a blinding flash of light. After several millennia, high schooler Taiju awakens and finds himself lost in a world of statues. However, he's not alone. His science-loving friend Senku's been up and running for a few months and he's got a grand plan...",
        videoSrc: "https://cdn.jwplayer.com/players/soQNOLoF-Twc0KgD2.html",
    },
    {
        id: 16,
        title: "JUJUTSU KAISEN",
        className:"jujutsu_kaisen",
        imageSrc: "/image/jujutsu.webp",
        category: "anime",
        subcategory: "action",
        movieDiscription:"Yuji Itadori, a kind-hearted teenager, joins his school's Occult Club for fun, but discovers that its members are actual sorcerers who can manipulate the energy between beings for their own use. He hears about a cursed talisman - the finger of Sukuna, a demon and its being targeted by other cursed beings...",
        videoSrc: "https://cdn.jwplayer.com/players/eNOfhjzP-Twc0KgD2.html",
    },
    {
        id: 17,
        title: "CHAINSAW MAN",
        className:"chainsaw_man",
        imageSrc: "/image/chainsaw.webp",
        category: "anime",
        subcategory: "action",
        movieDiscription:"When his father died, Denji was stuck with a huge debt and no way to pay it back. Thanks to a Devil dog he saved named Pochita, he's able to survive through odd jobs and killing Devils for the Yakuza. Pochita's chainsaw powers come in handy against these powerful demons. When the Yakuza betrays...",
        videoSrc: "https://cdn.jwplayer.com/players/7NYzEA8m-Twc0KgD2.html",
    },
    {
        id: 18,
        title: "RECORD OF RAGNAROK",
        className:"record_of_ragnarok",
        imageSrc: "/image/Ragnarok.webp",
        category: "anime",
        subcategory: "action",
        movieDiscription:"Every 1000 years, the Gods' Council assemble to decide the fate of humanity. After 7 million years of human history, the gods come to the decision that humans are irredeemable and must be extinct. However, the valkyrie Brunhild proposes that humanity must have one last chance to prove their...",
        videoSrc: "https://cdn.jwplayer.com/players/eiBMr1TZ-Twc0KgD2.html",
    },
    {
        id: 19,
        title: "SUZUME",
        className:"suzume interNationalMovie",
        imageSrc: "/image/suzume.webp",
        category: "anime",
        subcategory: "action",
        movieDiscription:"Suzume, a 17-year-old girl who lives in a quiet town in Kyushu, meets a young man on a journey looking for doors. Suzume follows him to a dilapidated building in the mountains and finds a free-standing, undisturbed door as if it alone were saved from devastation. Suzume feels drawn... ",
        videoSrc: "https://cdn.jwplayer.com/players/NWzMkC3S-Twc0KgD2.html",
    },
    {
        id: 20,
        title: "WEATHERING WITH YOU",
        className:"wearthering_with_you",
        imageSrc: "/image/weatheringWithYou.webp",
        category: "anime",
        subcategory: "action",
        movieDiscription:"during a period of exceptionally rainy weather, high-school boy Hodaka Morishima runs away from his troubled rural home to Tokyo and befriends an orphan girl who can manipulate the weather. This is the story of the world's secret that only she and I know...",
        videoSrc: "https://cdn.jwplayer.com/players/Hs55BKtt-Twc0KgD2.html",
    },
    {
        id: 21,
        title: "YOUR NAME",
        className:"your_name interNationalMovie",
        imageSrc: "/image/yourName.webp",
        category: "anime",
        subcategory: "action",
        movieDiscription:"Mitsuha is the daughter of the mayor of a small mountain town. She's a straightforward high school girl who lives with her sister and her grandmother and has no qualms about letting it be known that she's uninterested in Shinto rituals or helping her father's electoral campaign. Instead she dreams...",
        videoSrc: "https://cdn.jwplayer.com/players/Ea2vpskV-Twc0KgD2.html",
    },
]
export {All_Movie_SliderData};